### ISSUE TITLE
[Bug]: auto remove Stale label when issue updated with new comment

### ISSUE THREAD

**Issue by shun2wang** [juliuspf/jasp-issues#31]
### JASP Version

Others

### Commit ID

a7d4928c2decd3e28bff64c333db7ec3b78eee52

### JASP Module

Reliability

### What analysis are you seeing the problem on?

ssss

### What OS are you seeing the problem on?

Linux

### Bug Description

github-actions was not remove the stale labe after update comment.

### Expected Behaviour

The actions should auto remove the `Stale ` label when issue updated with new comment

### Steps to Reproduce

1.a
2.v
3.v
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Hi @juliuspf , this it's also a Feature request.

I filed here and you can do some test here.

**Comment by juliuspf** [comment]
you mean like here: https://github.com/jasp-stats/jasp-issues/pull/1901 ?

**Comment by shun2wang** [comment]
I mean this: https://github.com/jasp-stats/jasp-issues/issues/1844#issuecomment-1314914588

because in action comment we says:
> Feel free to leave a comment if you believe this is still relevant.

So what ever user comment to update the issue action should auto remove stale label and reset timer.

**Comment by juliuspf** [comment]
I saw that, yes. You are right

**Comment by juliuspf** [comment]
hmm, this should actually be working: https://github.com/actions/stale#remove-stale-when-updated the default is true

**Comment by juliuspf** [comment]
Ah, I think this will just be updated once the action runs again, which will be tomorrow morning actually. Maybe lets wait for that and see if the issue persists

**Comment by juliuspf** [comment]
I reran the action, and you see that the label is removed: https://github.com/jasp-stats/jasp-issues/issues/1844

**Comment by juliuspf** [comment]
so I think it is all good

**Comment by juliuspf** [comment]
thanks for thinking along though :)

**Comment by shun2wang** [comment]
thank you.
